// Code generated by protoc-gen-go. DO NOT EDIT.
// source: details.proto

package userdetails

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message asking for the user's details with default values.
type UserDetailsRequest struct {
	Properties           []byte   `protobuf:"bytes,1,opt,name=Properties,proto3" json:"Properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetailsRequest) Reset()         { *m = UserDetailsRequest{} }
func (m *UserDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*UserDetailsRequest) ProtoMessage()    {}
func (*UserDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c457112169d4fb2c, []int{0}
}

func (m *UserDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailsRequest.Unmarshal(m, b)
}
func (m *UserDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailsRequest.Marshal(b, m, deterministic)
}
func (m *UserDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailsRequest.Merge(m, src)
}
func (m *UserDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_UserDetailsRequest.Size(m)
}
func (m *UserDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailsRequest proto.InternalMessageInfo

func (m *UserDetailsRequest) GetProperties() []byte {
	if m != nil {
		return m.Properties
	}
	return nil
}

// The response message containing the user details
type UserDetailsReply struct {
	Details              []byte   `protobuf:"bytes,1,opt,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetailsReply) Reset()         { *m = UserDetailsReply{} }
func (m *UserDetailsReply) String() string { return proto.CompactTextString(m) }
func (*UserDetailsReply) ProtoMessage()    {}
func (*UserDetailsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c457112169d4fb2c, []int{1}
}

func (m *UserDetailsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailsReply.Unmarshal(m, b)
}
func (m *UserDetailsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailsReply.Marshal(b, m, deterministic)
}
func (m *UserDetailsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailsReply.Merge(m, src)
}
func (m *UserDetailsReply) XXX_Size() int {
	return xxx_messageInfo_UserDetailsReply.Size(m)
}
func (m *UserDetailsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailsReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailsReply proto.InternalMessageInfo

func (m *UserDetailsReply) GetDetails() []byte {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*UserDetailsRequest)(nil), "userdetails.UserDetailsRequest")
	proto.RegisterType((*UserDetailsReply)(nil), "userdetails.UserDetailsReply")
}

func init() { proto.RegisterFile("details.proto", fileDescriptor_c457112169d4fb2c) }

var fileDescriptor_c457112169d4fb2c = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x49, 0x2d, 0x49,
	0xcc, 0xcc, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2e, 0x2d, 0x4e, 0x2d, 0x82,
	0x0a, 0x29, 0x99, 0x70, 0x09, 0x85, 0x16, 0xa7, 0x16, 0xb9, 0x40, 0xb8, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x42, 0x72, 0x5c, 0x5c, 0x01, 0x45, 0xf9, 0x05, 0xa9, 0x45, 0x25, 0x99, 0xa9,
	0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x48, 0x22, 0x4a, 0x3a, 0x5c, 0x02, 0x28, 0xba,
	0x0a, 0x72, 0x2a, 0x85, 0x24, 0xb8, 0xd8, 0xa1, 0x7c, 0xa8, 0x06, 0x18, 0xd7, 0x28, 0x91, 0x8b,
	0x1b, 0x49, 0xb5, 0x50, 0x10, 0x17, 0x9f, 0x7b, 0x6a, 0x09, 0xb2, 0x88, 0xbc, 0x1e, 0x92, 0x93,
	0xf4, 0x30, 0xdd, 0x23, 0x25, 0x8b, 0x5b, 0x41, 0x41, 0x4e, 0xa5, 0x12, 0x43, 0x12, 0x1b, 0xd8,
	0x6b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xea, 0x8b, 0x5e, 0xeb, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserDetailsClient is the client API for UserDetails service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserDetailsClient interface {
	GetUserDetails(ctx context.Context, in *UserDetailsRequest, opts ...grpc.CallOption) (*UserDetailsReply, error)
}

type userDetailsClient struct {
	cc *grpc.ClientConn
}

func NewUserDetailsClient(cc *grpc.ClientConn) UserDetailsClient {
	return &userDetailsClient{cc}
}

func (c *userDetailsClient) GetUserDetails(ctx context.Context, in *UserDetailsRequest, opts ...grpc.CallOption) (*UserDetailsReply, error) {
	out := new(UserDetailsReply)
	err := c.cc.Invoke(ctx, "/userdetails.UserDetails/GetUserDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDetailsServer is the server API for UserDetails service.
type UserDetailsServer interface {
	GetUserDetails(context.Context, *UserDetailsRequest) (*UserDetailsReply, error)
}

func RegisterUserDetailsServer(s *grpc.Server, srv UserDetailsServer) {
	s.RegisterService(&_UserDetails_serviceDesc, srv)
}

func _UserDetails_GetUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsServer).GetUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userdetails.UserDetails/GetUserDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsServer).GetUserDetails(ctx, req.(*UserDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDetails_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userdetails.UserDetails",
	HandlerType: (*UserDetailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserDetails",
			Handler:    _UserDetails_GetUserDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "details.proto",
}
